name: FrameCasesRecode
version: 1.0.0
main: ru.paimonsoft.framecaserecode.FrameCasesRecode
api-version: '1.16'
depend:
  - ProtocolLib
  - HolographicDisplays
authors:
  - PaimonSoft Team
website: https://discord.paimonsoft.xyz/
commands:
  framecases:
    aliases:
      - cases